version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - mongo

  datamanager:
    image: ${DOCKER_REGISTRY-}datamanager
    build:
      context: .
      dockerfile: DataManager/Dockerfile
    restart: always
    ports:
      - 15933:80
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo

  controlpanel:
    image: ${DOCKER_REGISTRY-}controlpanel
    build:
      context: .
      dockerfile: ControlPanel/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8024:80
    depends_on:
      - datamanager
