version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo

  datamanager:
    image: ${DOCKER_REGISTRY-}datamanager
    build:
      context: .
      dockerfile: DataManager/Dockerfile
    restart: always
    ports:
      - 5000:80
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo

  controlpanel:
    image: ${DOCKER_REGISTRY-}controlpanel
    build:
      context: .
      dockerfile: ControlPanel/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8080:80
    depends_on:
      - datamanager
